apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ace-minimal-build-image-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-minimal-build-image-pipeline
  params:
    - name: dockerRegistry
      value: "us.icr.io/ace-registry"