apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-cluster
spec:
  params:
    - name: dockerRegistry
      type: string
    - name: url
      type: string
    - name: revision
      type: string
    - name: tag
      type: string
  steps:
    - name: clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
      script: |
        #!/bin/sh
        set -x
        cd /work
        git clone -b $(params.revision) $(params.url)
        export REG_WITH_ESCAPED_SLASH=`echo $(params.dockerRegistry) | sed 's/\//\\\\\\//g'`
        echo $REG_WITH_ESCAPED_SLASH
        sed -i "s/DOCKER_REGISTRY/$REG_WITH_ESCAPED_SLASH/g" /work/ace-keda-demo/tekton/ace-keda-demo-tekton-deployment.yaml
        export TAG=$(params.tag)
        echo Using $TAG as image tag
        sed -i "s/IMAGE_TAG/$TAG/g" /work/ace-keda-demo/tekton/*.yaml
        cat /work/ace-keda-demo/tekton/ace-keda-demo-tekton-deployment.yaml
      volumeMounts:
        - mountPath: /work
          name: work
    - name: deploy-app
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/work/ace-keda-demo/tekton/ace-keda-demo-tekton-deployment.yaml"
      volumeMounts:
        - mountPath: /work
          name: work
  volumes:
    - name: work
      emptyDir: {}
