apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ace-keda-demo-pipeline-run-
  # Fixed name allows "tkn pr delete ace-pipeline-run-1 -f ; kubectl apply -f tekton/ace-pipeline-run.yaml ; tkn pr logs ace-pipeline-run-1 -f"
  #name: ace-keda-demo-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-keda-demo-pipeline
  params:
    - name: outputRegistry
      # OpenShift
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
      #value: "quay.io/trevor_dolby"
      #value: "us.icr.io/ace-containers"
      #value: "aceDemoRegistry.azurecr.io"
      # Minikube
      #value: "192.168.49.2:5000/default"
    - name: buildImage
      # ace-minimal can be built from the ACE package without needing a key
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal:13.0.1.0-alpine-mqclient"
      # Minikube      
      #value: "192.168.49.2:5000/default/ace-minimal:13.0.1.0-alpine-mqclient"
    - name: runtimeBaseImage
      # ace-minimal can be built from the ACE package without needing a key
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal:13.0.1.0-alpine-mqclient"
      # Minikube
      #value: "192.168.49.2:5000/default/ace-minimal:13.0.1.0-alpine-mqclient"
    - name: url
      value: "https://github.com/tdolby-at-uk-ibm-com/ace-keda-demo"
    - name: revision
      value: "v13-update"