apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-keda-demo
spec:
  selector:
    matchLabels:
      app: ace-keda-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: ace-keda-demo
    spec:
      volumes:
      - name: secret-volume-2
        secret:
          secretName: mq-secret
      containers:
      - name: ace-keda-demo
        image: DOCKER_REGISTRY/ace-keda-demo:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume-2
          mountPath: /var/run/secrets/mq
        env:
        - name: KEDA_MQ_USER
          valueFrom:
            secretKeyRef:
              name: keda-ibmmq-secret
              key: ADMIN_USER
        - name: KEDA_MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keda-ibmmq-secret
              key: ADMIN_PASSWORD
