apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ace-keda-demo
  namespace: default
  labels:
    deploymentName: ace-keda-demo
spec:
  scaleTargetRef:
    name: ace-keda-demo
  pollingInterval: 10 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  maxReplicaCount: 4 # Optional. Default: 100
  triggers:
    - type: ibmmq
      metadata:
        host: 'https://web-mqoc-fd48.qm.us-south.mq.appdomain.cloud/ibmmq/rest/v3/admin/action/qmgr/MQoC/mqsc'
        queueManager: 'MQoC' # Your queue manager
        queueName: 'DEMO.QUEUE' # Your queue name
      authenticationRef:
        name: ace-keda-demo-trigger
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: ace-keda-demo-trigger
  namespace: default
spec:
  secretTargetRef:
    - parameter: username
      name: keda-ibmmq-secret
      key: ADMIN_USER
    - parameter: password
      name: keda-ibmmq-secret
      key: ADMIN_PASSWORD
