apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm-dev
spec:
  license:
    accept: true
    license: L-CLXQ-ADXTK3
    use: Development
  web:
    enabled: true
  pki:
    keys:
      - name: qmdevtls
        secret:
          secretName: qm-dev-tls
          items: 
          - tls.key
          - tls.crt
  template:
    pod:
      containers:
        - env:
            - name: MQ_DEV
              value: "true"
            - name: MQ_CONNAUTH_USE_HTP
              value: "true"
            # oc create secret generic qm-dev-passwords --from-literal=dev-admin-password=passw0rd --from-literal=dev-app-password=passw0rd
            - name: MQ_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qm-dev-passwords
                  key: dev-admin-password
            - name: MQ_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qm-dev-passwords
                  key: dev-app-password
          name: qmgr
  queueManager:
    storage:
      queueManager:
        type: persistent-claim
    name: QUICKSTART
  version: 9.4.0.6-r1
