apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qm-dev-certificate
spec:
  # Secret names are always required.
  secretName: qm-dev-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - cert-manager

  # Avoid using commonName for DNS names in end-entity (leaf) certificates. Unless you have a specific
  # need for it in your environment, use dnsNames exclusively to avoid issues with commonName.
  # Usually, commonName is used to give human-readable names to CA certificates and can be avoided for
  # other certificates.
  commonName: qm-dev

  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer

# Install the "cert-manager Operator for Red Hat OpenShift" operator
# Configure a signing key (possibly by copying csr-signer from the
# openshift-kube-controller-manager-operator namespace into ca-root-secret
